import locale
import os

# Diccionario de traducciones
MESSAGES = {
    "es": {
        "command_help": "Genera un archivo requirements.txt basado en análisis estático y de configuración.",
        "arg_output_help": "Nombre del archivo de salida (por defecto: requirements.txt)",
        "arg_validate_help": "Valida el archivo generado en un entorno temporal.",
        "arg_develop_help": "Ruta local del código del plugin para instalarlo durante la validación (modo desarrollo).",
        "start_gen": "Iniciando generación de {file}...",
        "scan_ast": "Escaneando código fuente (AST)...",
        "scan_django": "Inspeccionando configuraciones de Django...",
        "load_dynamic": "Cargando hallazgos dinámicos previos...",
        "filter_map": "Filtrando librería estándar y mapeando a paquetes...",
        "backup_created": "Archivo existente respaldado en: {backup}",
        "write_success": "Archivo {file} generado con {count} dependencias.",
        "header_autogen": "# Archivo autogenerado por django-req-generator",
        "header_repo": "# Repositorio: https://github.com/oscar/django-req-generator",
        "validate_start": "Validando requisitos en entorno temporal...",
        "validate_success": "¡Validación exitosa! El proyecto arranca correctamente.",
        "validate_error": "Error de validación:\n{output}",
        "error_no_manage": "No se encontró manage.py para validar.",
        "log_create_venv": "Creando entorno virtual temporal en: {path}",
        "log_install_plugin": "Instalando el plugin local desde: {path}",
        "log_install_reqs": "Instalando dependencias desde: {file}",
        "log_running_check": "Ejecutando 'python manage.py check' con settings: {settings}",
        "warn_production": "¡ADVERTENCIA!: El flag --validate crea un entorno virtual temporal y realiza instalaciones. NO se recomienda su uso en servidores de producción reales.",
        "prompt_continue": "¿Desea continuar con la validación? (S/n): ",
        "validate_skipped": "Validación saltada por el usuario.",
        "prompt_missing_module": "Se detectó que falta el módulo '{module}'. ¿Desea agregarlo a los requisitos y reintentar? (S/n): ",
    },
    "en": {
        "command_help": "Generates a requirements.txt file based on static and configuration analysis.",
        "arg_output_help": "Output filename (default: requirements.txt)",
        "arg_validate_help": "Validates the generated file in a temporary environment.",
        "arg_develop_help": "Local path of the plugin source code for installation during validation (development mode).",
        "start_gen": "Starting generation for {file}...",
        "scan_ast": "Scanning source code (AST)...",
        "scan_django": "Inspecting Django configurations...",
        "load_dynamic": "Loading previous dynamic findings...",
        "filter_map": "Filtering standard library and mapping to packages...",
        "backup_created": "Existing file backed up to: {backup}",
        "write_success": "File {file} generated with {count} dependencies.",
        "header_autogen": "# File auto-generated by django-req-generator",
        "header_repo": "# Repository: https://github.com/oscar/django-req-generator",
        "validate_start": "Validating requirements in temporary environment...",
        "validate_success": "Validation successful! The project starts correctly.",
        "validate_error": "Validation error:\n{output}",
        "error_no_manage": "manage.py was not found for validation.",
        "log_create_venv": "Creating temporary virtual environment in: {path}",
        "log_install_plugin": "Installing local plugin from: {path}",
        "log_install_reqs": "Installing dependencies from: {file}",
        "log_running_check": "Running 'python manage.py check' with settings: {settings}",
        "warn_production": "WARNING!: The --validate flag creates a temporary virtual environment and performs installations. It is NOT recommended for use on real production servers.",
        "prompt_continue": "Do you want to continue with validation? (Y/n): ",
        "validate_skipped": "Validation skipped by user.",
        "prompt_missing_module": "Module '{module}' was detected as missing. Would you like to add it to requirements and retry? (Y/n): ",
    }
}

def get_language():
    """Detecta el idioma del sistema."""
    # Primero intentar con la variable de entorno
    lang_env = os.environ.get("LANG", "").split(".")[0].split("_")[0].lower()
    if lang_env in MESSAGES:
        return lang_env
    
    # Después intentar con locale
    try:
        lang_loc, _ = locale.getdefaultlocale()
        if lang_loc:
            lang_loc = lang_loc.split("_")[0].lower()
            if lang_loc in MESSAGES:
                return lang_loc
    except Exception:
        pass
        
    return "es"  # Por defecto español

CURRENT_LANG = get_language()

def _(key, **kwargs):
    """Traduce la clave según el idioma detectado."""
    text = MESSAGES.get(CURRENT_LANG, MESSAGES["es"]).get(key, key)
    if kwargs:
        return text.format(**kwargs)
    return text
